# Generated by Django 3.1 on 2020-08-20 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_auto_20200820_1036'),
        ('users', '0002_auto_20200820_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hood.neighbourhood'),
        ),
    ]
