# Generated by Django 3.1 on 2020-08-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='fire_dept',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='health_eme',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_cont',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
